version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/ios-file-uploader
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    command: ["postgres", "-p", "5433"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ios-file-uploader -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ios-file-uploader
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ios_file_uploader_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: '2gb'
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
    ports:
      - "4444:4444"
volumes:
  ios_file_uploader_postgres_data: