version: '3.8'

services:
  app:
    image: iceteagreen/ios-file-uploader:latest
    # ... existing ports, networks, etc ...
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/ios-file-uploader
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: 30000
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    networks:
      - grpc-network-1
  db:
    image: postgres:15-alpine
    command: ["postgres", "-p", "5433"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ios-file-uploader -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ios-file-uploader
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ios_file_uploader_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - grpc-network-1
networks:
  grpc-network-1:
    external: true
volumes:
  ios_file_uploader_postgres_data: