server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: ios-file-uploader
  datasource:
    url: jdbc:postgresql://localhost:5433/ios-file-uploader?autoReconnect=true
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000 # 30 seconds
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000 # 10 minutes
      max-lifetime: 1800000 # 30 minutes
      connection-test-query: SELECT 1
      auto-commit: true
      initialization-fail-timeout: 30000
    jpa:
      hibernate:
        ddl-auto: validate
        show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

  flyway:
    url: jdbc:postgresql://localhost:5433/ios-file-uploader
    user: admin
    password: admin
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
    connect-retries: 10           # Number of retries
    connect-retries-interval: 5s  # Interval between retries
grpc:
  client:
    file-storage:
      address: static://localhost:9090
      negotiationType: plaintext

file-storage-base-url: http://localhost:8080
file-max-size: 4194304
buffer-size: 4096
chunk-size: 65536
grpc-server:
  domain: localhost
  port: 9090