server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: ios-file-uploader
  datasource:
    url: jdbc:postgresql://db:5433/ios-file-uploader
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
        show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

  flyway:
    url: jdbc:postgresql://db:5433/ios-file-uploader
    user: admin
    password: admin
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true